package luna.rpg

import org.yaml.snakeyaml.DumperOptions
import org.yaml.snakeyaml.Yaml
import org.yaml.snakeyaml.nodes.Tag
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.PrintWriter

class RpgConfigLoader(
    private val configPath: String = "config.yml",
) {
    fun load(): RpgConfigData {
        val configFile = File(configPath)
        if (!configFile.exists()) {
            val defaultConfig = RpgConfigData()
            save(defaultConfig)
            return defaultConfig
        }

        val yaml = Yaml()
        val inputStream = FileInputStream(configFile)
        val data = yaml.loadAs(inputStream, Map::class.java) as Map<String, Any>

        return parseConfig(data)
    }

    private fun save(config: RpgConfigData) {
        val configFile = File(configPath)
        val writer = PrintWriter(configFile)

        writer.println("# Luna Discord RPG Configuration")
        writer.println("# This file is automatically generated. You can modify it to change game balance.")
        writer.println()

        writer.println("# --- Exploration Settings ---")
        writer.println("exploration:")
        writer.println("  # The size of each floor (number of rooms/steps)")
        writer.println("  floor_size: ${config.exploration.floorSize}")
        writer.println("  # The threshold for resource event roll (0-100)")
        writer.println("  event_roll_resource_threshold: ${config.exploration.eventRollResourceThreshold}")
        writer.println("  # Minimum resource amount per find")
        writer.println("  resource_min_amount: ${config.exploration.resourceMinAmount}")
        writer.println("  # Maximum resource amount per find")
        writer.println("  resource_max_amount: ${config.exploration.resourceMaxAmount}")
        writer.println("  # Names of resources")
        writer.println("  resource_names:")
        config.exploration.resourceNames.forEach { writer.println("    - \"$it\"") }
        writer.println("  # Names of monsters encountered")
        writer.println("  monster_names:")
        config.exploration.monsterNames.forEach { writer.println("    - \"$it\"") }
        writer.println()

        writer.println("# --- Monster Settings ---")
        writer.println("monster:")
        writer.println("  base_hp: ${config.monster.baseHp}")
        writer.println("  hp_per_floor: ${config.monster.hpPerFloor}")
        writer.println("  base_atk: ${config.monster.baseAtk}")
        writer.println("  atk_per_floor: ${config.monster.atkPerFloor}")
        writer.println("  base_def: ${config.monster.baseDef}")
        writer.println("  def_per_floor: ${config.monster.defPerFloor}")
        writer.println("  base_spd: ${config.monster.baseSpd}")
        writer.println("  spd_per_floor: ${config.monster.spdPerFloor}")
        writer.println()

        writer.println("# --- Combat Settings ---")
        writer.println("combat:")
        writer.println("  # Maximum turns in a single combat session")
        writer.println("  max_turns: ${config.combat.maxTurns}")
        writer.println()

        writer.println("# --- Economy Settings ---")
        writer.println("economy:")
        writer.println("  # Requirements for upgrades (item -> resource -> amount)")
        writer.println("  upgrade_requirements:")
        config.economy.upgradeRequirements.forEach { (item, reqs) ->
            writer.println("    $item:")
            reqs.forEach { (res, amount) ->
                writer.println("      $res: $amount")
            }
        }
        writer.println("  # Base reward for defeating a monster")
        writer.println("  monster_reward_base_amount: ${config.economy.monsterRewardBaseAmount}")
        writer.println("  # Reward scaling per floor")
        writer.println("  monster_reward_scale_per_floor: ${config.economy.monsterRewardScalePerFloor}")
        writer.println()

        writer.println("# --- Upgrade Bonus Settings ---")
        writer.println("upgrade:")
        writer.println("  weapon_atk_bonus: ${config.upgrade.weaponAtkBonus}")
        writer.println("  shield_def_bonus: ${config.upgrade.shieldDefBonus}")
        writer.println("  armor_hp_bonus: ${config.upgrade.armorHpBonus}")
        writer.println("  # How many seconds each recovery upgrade reduces")
        writer.println("  recovery_reduction_seconds: ${config.upgrade.recoveryReductionSeconds}")
        writer.println()

        writer.println("# --- Recovery Settings ---")
        writer.println("recovery:")
        writer.println("  # Base seconds needed to recover 1 HP")
        writer.println("  base_seconds_per_hp: ${config.recovery.baseSecondsPerHp}")
        writer.println("  # Minimum total recovery time")
        writer.println("  min_seconds: ${config.recovery.minSeconds}")
        writer.println()

        writer.println("# --- Rebirth Settings ---")
        writer.println("rebirth:")
        writer.println("  # Minimum floor reached to enable rebirth")
        writer.println("  min_floor: ${config.rebirth.minFloor}")
        writer.println("  # Floor interval for earning rebirth points")
        writer.println("  milestone_interval: ${config.rebirth.milestoneInterval}")
        writer.println("  # Points earned per milestone")
        writer.println("  points_per_milestone: ${config.rebirth.pointsPerMilestone}")
        writer.println("  # Base cost of rebirth stat upgrades")
        writer.println("  base_upgrade_cost: ${config.rebirth.baseUpgradeCost}")
        writer.println("  # Cost increase per level of rebirth upgrade")
        writer.println("  cost_increase_per_level: ${config.rebirth.costIncreasePerLevel}")
        writer.println("  # Maximum level for each rebirth stat")
        writer.println("  max_stat_level: ${config.rebirth.maxStatLevel}")
        writer.println("  # Percentage bonus per rebirth level (e.g., 0.05 = +5%)")
        writer.println("  stat_bonus_per_level: ${config.rebirth.statBonusPerLevel}")
        writer.println("  # Maximum level for resource gain upgrade")
        writer.println("  max_resource_level: ${config.rebirth.maxResourceLevel}")
        writer.println("  # Bonus per resource gain level")
        writer.println("  resource_bonus_per_level: ${config.rebirth.resourceBonusPerLevel}")
        writer.println("  # Maximum level for efficiency upgrade")
        writer.println("  max_efficient_level: ${config.rebirth.maxEfficientLevel}")
        writer.println("  # Bonus per efficiency level")
        writer.println("  efficient_bonus_per_level: ${config.rebirth.efficientBonusPerLevel}")
        writer.println()

        writer.println("# --- Player Initial Attributes ---")
        writer.println("player:")
        writer.println("  initial_hp: ${config.player.initialHp}")
        writer.println("  initial_atk: ${config.player.initialAtk}")
        writer.println("  initial_def: ${config.player.initialDef}")
        writer.println("  initial_spd: ${config.player.initialSpd}")
        writer.println("  initial_resources: ${config.player.initialResources}")
        writer.println()

        writer.println("# --- Map Settings ---")
        writer.println("map:")
        writer.println("  base_wood_cost: ${config.map.baseWoodCost}")
        writer.println("  base_stone_cost: ${config.map.baseStoneCost}")
        writer.println("  base_metal_cost: ${config.map.baseMetalCost}")
        writer.println("  cost_scale_per_layer: ${config.map.costScalePerLayer}")
        writer.println("  min_drop_rate: ${config.map.minDropRate}")
        writer.println("  max_drop_rate: ${config.map.maxDropRate}")

        writer.close()
    }

    private fun parseConfig(data: Map<String, Any>): RpgConfigData {
        val exploration = data["exploration"] as? Map<String, Any>
        val monster = data["monster"] as? Map<String, Any>
        val combat = data["combat"] as? Map<String, Any>
        val economy = data["economy"] as? Map<String, Any>
        val upgrade = data["upgrade"] as? Map<String, Any>
        val recovery = data["recovery"] as? Map<String, Any>
        val rebirth = data["rebirth"] as? Map<String, Any>
        val player = data["player"] as? Map<String, Any>
        val map = data["map"] as? Map<String, Any>

        return RpgConfigData(
            exploration =
                ExplorationConfig(
                    floorSize = exploration?.get("floor_size") as? Int ?: 5,
                    eventRollResourceThreshold = exploration?.get("event_roll_resource_threshold") as? Int ?: 50,
                    resourceMinAmount = exploration?.get("resource_min_amount") as? Int ?: 1,
                    resourceMaxAmount = exploration?.get("resource_max_amount") as? Int ?: 5,
                    resourceNames = exploration?.get("resource_names") as? List<String> ?: listOf("🪵 木頭", "🪨 石頭", "🔗 金屬"),
                    monsterNames = exploration?.get("monster_names") as? List<String> ?: listOf("史萊姆", "哥布林", "小蝙蝠"),
                ),
            monster =
                MonsterConfig(
                    baseHp = monster?.get("base_hp") as? Int ?: 20,
                    hpPerFloor = monster?.get("hp_per_floor") as? Int ?: 5,
                    baseAtk = monster?.get("base_atk") as? Int ?: 5,
                    atkPerFloor = monster?.get("atk_per_floor") as? Int ?: 2,
                    baseDef = monster?.get("base_def") as? Int ?: 2,
                    defPerFloor = monster?.get("def_per_floor") as? Int ?: 1,
                    baseSpd = monster?.get("base_spd") as? Int ?: 3,
                    spdPerFloor = monster?.get("spd_per_floor") as? Int ?: 1,
                ),
            combat =
                CombatConfig(
                    maxTurns = combat?.get("max_turns") as? Int ?: 20,
                ),
            economy =
                EconomyConfig(
                    upgradeRequirements =
                        economy?.get("upgrade_requirements") as? Map<String, Map<String, Int>> ?: mapOf(
                            "weapon" to mapOf("wood" to 10, "metal" to 5),
                            "shield" to mapOf("stone" to 10, "metal" to 5),
                            "armor" to mapOf("wood" to 5, "stone" to 10),
                            "recovery" to mapOf("wood" to 10, "stone" to 10, "metal" to 10),
                        ),
                    monsterRewardBaseAmount = economy?.get("monster_reward_base_amount") as? Int ?: 2,
                    monsterRewardScalePerFloor = economy?.get("monster_reward_scale_per_floor") as? Int ?: 1,
                ),
            upgrade =
                UpgradeConfig(
                    weaponAtkBonus = upgrade?.get("weapon_atk_bonus") as? Int ?: 5,
                    shieldDefBonus = upgrade?.get("shield_def_bonus") as? Int ?: 5,
                    armorHpBonus = upgrade?.get("armor_hp_bonus") as? Int ?: 5,
                    recoveryReductionSeconds = (upgrade?.get("recovery_reduction_seconds") as? Number)?.toDouble() ?: 5.0,
                ),
            recovery =
                RecoveryConfig(
                    baseSecondsPerHp = (recovery?.get("base_seconds_per_hp") as? Number)?.toDouble() ?: 0.1,
                    minSeconds = (recovery?.get("min_seconds") as? Number)?.toDouble() ?: 5.0,
                ),
            rebirth =
                RebirthConfig(
                    minFloor = rebirth?.get("min_floor") as? Int ?: 50,
                    milestoneInterval = rebirth?.get("milestone_interval") as? Int ?: 10,
                    pointsPerMilestone = rebirth?.get("points_per_milestone") as? Int ?: 1,
                    baseUpgradeCost = rebirth?.get("base_upgrade_cost") as? Int ?: 1,
                    costIncreasePerLevel = rebirth?.get("cost_increase_per_level") as? Int ?: 1,
                    maxStatLevel = rebirth?.get("max_stat_level") as? Int ?: 10,
                    statBonusPerLevel = (rebirth?.get("stat_bonus_per_level") as? Number)?.toDouble() ?: 0.05,
                    maxResourceLevel = rebirth?.get("max_resource_level") as? Int ?: 10,
                    resourceBonusPerLevel = (rebirth?.get("resource_bonus_per_level") as? Number)?.toDouble() ?: 0.05,
                    maxEfficientLevel = rebirth?.get("max_efficient_level") as? Int ?: 10,
                    efficientBonusPerLevel = (rebirth?.get("efficient_bonus_per_level") as? Number)?.toDouble() ?: 0.05,
                ),
            player =
                PlayerConfig(
                    initialHp = player?.get("initial_hp") as? Int ?: 100,
                    initialAtk = player?.get("initial_atk") as? Int ?: 10,
                    initialDef = player?.get("initial_def") as? Int ?: 5,
                    initialSpd = player?.get("initial_spd") as? Int ?: 8,
                    initialResources = player?.get("initial_resources") as? Int ?: 0,
                ),
            map =
                MapConfig(
                    baseWoodCost = map?.get("base_wood_cost") as? Int ?: 100,
                    baseStoneCost = map?.get("base_stone_cost") as? Int ?: 100,
                    baseMetalCost = map?.get("base_metal_cost") as? Int ?: 50,
                    costScalePerLayer = (map?.get("cost_scale_per_layer") as? Number)?.toDouble() ?: 1.0,
                    minDropRate = (map?.get("min_drop_rate") as? Number)?.toDouble() ?: 0.6,
                    maxDropRate = (map?.get("max_drop_rate") as? Number)?.toDouble() ?: 1.5,
                ),
        )
    }
}

data class RpgConfigData(
    val exploration: ExplorationConfig = ExplorationConfig(),
    val monster: MonsterConfig = MonsterConfig(),
    val combat: CombatConfig = CombatConfig(),
    val economy: EconomyConfig = EconomyConfig(),
    val upgrade: UpgradeConfig = UpgradeConfig(),
    val recovery: RecoveryConfig = RecoveryConfig(),
    val rebirth: RebirthConfig = RebirthConfig(),
    val player: PlayerConfig = PlayerConfig(),
    val map: MapConfig = MapConfig(),
)

data class ExplorationConfig(
    val floorSize: Int = 5,
    val eventRollResourceThreshold: Int = 50,
    val resourceMinAmount: Int = 1,
    val resourceMaxAmount: Int = 5,
    val resourceNames: List<String> = listOf("🪵 木頭", "🪨 石頭", "🔗 金屬"),
    val monsterNames: List<String> = listOf("史萊姆", "哥布林", "小蝙蝠"),
)

data class MonsterConfig(
    val baseHp: Int = 20,
    val hpPerFloor: Int = 5,
    val baseAtk: Int = 5,
    val atkPerFloor: Int = 2,
    val baseDef: Int = 2,
    val defPerFloor: Int = 1,
    val baseSpd: Int = 3,
    val spdPerFloor: Int = 1,
)

data class CombatConfig(
    val maxTurns: Int = 20,
)

data class EconomyConfig(
    val upgradeRequirements: Map<String, Map<String, Int>> =
        mapOf(
            "weapon" to mapOf("wood" to 10, "metal" to 5),
            "shield" to mapOf("stone" to 10, "metal" to 5),
            "armor" to mapOf("wood" to 5, "stone" to 10),
            "recovery" to mapOf("wood" to 10, "stone" to 10, "metal" to 10),
        ),
    val monsterRewardBaseAmount: Int = 2,
    val monsterRewardScalePerFloor: Int = 1,
)

data class UpgradeConfig(
    val weaponAtkBonus: Int = 5,
    val shieldDefBonus: Int = 5,
    val armorHpBonus: Int = 5,
    val recoveryReductionSeconds: Double = 5.0,
)

data class RecoveryConfig(
    val baseSecondsPerHp: Double = 0.1,
    val minSeconds: Double = 5.0,
)

data class RebirthConfig(
    val minFloor: Int = 50,
    val milestoneInterval: Int = 10,
    val pointsPerMilestone: Int = 1,
    val baseUpgradeCost: Int = 1,
    val costIncreasePerLevel: Int = 1,
    val maxStatLevel: Int = 10,
    val statBonusPerLevel: Double = 0.05,
    val maxResourceLevel: Int = 10,
    val resourceBonusPerLevel: Double = 0.05,
    val maxEfficientLevel: Int = 10,
    val efficientBonusPerLevel: Double = 0.05,
)

data class PlayerConfig(
    val initialHp: Int = 100,
    val initialAtk: Int = 10,
    val initialDef: Int = 5,
    val initialSpd: Int = 8,
    val initialResources: Int = 0,
)

data class MapConfig(
    val baseWoodCost: Int = 100,
    val baseStoneCost: Int = 100,
    val baseMetalCost: Int = 50,
    val costScalePerLayer: Double = 1.0,
    val minDropRate: Double = 0.6,
    val maxDropRate: Double = 1.5,
)
